### PR TITLE
Added game deny button

### PR DESCRIPTION
**Pull request by stubailo**
Right now, it completely deletes the game.  Ideally, there would be some way to see denied games, but we can save that for later.

### CODE REVIEW

**Comment by stubailo** [comment]
should resolve #101

**Comment by vpontis** [comment]
Seems like the right functionality. It's too hard to delete and undelete games. 

But I think you should be able to deny a game even if you are not able to confirm it. So you should be able to deny pending games.

**Comment by stubailo** [comment]
So right now there is no way to view pending games, and I think adding that feature is too much work. In the cancan permissions, though, you are allowed to delete pending games.  However you would have to manually create the http request :]

**Comment by vpontis** [comment]
Is it a lot of work to look at pending games? It's a game of yours that's not confirmed but you can't confirm, right? Shouldn't be too much.

**Comment by stubailo** [comment]
I just mean like, where in the UI would that go? it adds more complexity for what I think is not that much of an upgrade in features

**Comment by stubailo** [comment]
can we merge this in for now and I'll add that UI stuff later, I think it'll be part of the groups rework

**Comment by vpontis** [comment]
sure

## 

VPontis

**Pull request merged**
