### PR TITLE
Feature parametrized username

### PR DESCRIPTION
**Pull request by vpontis**
one of the tests that updates the parameterized username isn't passing. this needs to be looked at.

### CODE REVIEW

**Comment by vpontis** [comment]
#68

**Comment by stubailo** [comment]
OK I see that the test is failing, looking into it

**Comment by stubailo** [comment]
Yo, in the tests make sure to use player.save! instead of player.save.  Player.save fails silently but save! throws an error: ActiveRecord::RecordInvalid: Validation failed: Username has already been taken

**Comment by stubailo** [comment]
You didn't push a migration, can't merge until you do

**Comment by vpontis** [comment]
Yea I did. What's wrong with my migration?

**Comment by vpontis** [comment]
@stubailo good to merge?

**Pull request merged**
