### PR TITLE
New sort games

### PR DESCRIPTION
**Pull request by dsessoms**
created a new branch because i just couldnt fix the other. This one sorts both all games and confirmed games. My apologies

### CODE REVIEW

**Comment by vpontis** [comment]
why did all of this append to the groups branch? why didnt you branch off master?

**Comment by vpontis** [comment]
also, we should probably also sort unconfirmed games... it's not very much code. can you make it so that this branch is off of develop? idk what happened here.

**Comment by dsessoms** [comment]
Idk what happened i was branching off of develop. and i don't think we should sort unconfirmed games because you want people to confirm older games first

**Comment by vpontis** [comment]
yea, well then we want to sort from older to newer, right?

## 

VPontis

**Comment by dsessoms** [comment]
oh damn, i forgot that we were appending the list of winning and losing games together. otherwise that would be done automatically. my b

**Pull request closed without merging**
